const products = [
    new ProductClass(
        0,
        'card_1.jpg',
        'Product 0',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        52.00,
    ),
    new ProductClass(
        1,
        'card_7.jpg',
        'Product 1',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        32.00,
    ),
    new ProductClass(
        2,
        'card_3.jpg',
        'Product 2',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        42.00,
    ),
    new ProductClass(
        3,
        'card_4.jpg',
        'Product 3',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        62.00,
    ),
    new ProductClass(
        4,
        'card_8.jpg',
        'Product 4',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        12.00,
    ),
    new ProductClass(
        5,
        'card_9.jpg',
        'Product 5',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        72.00,
    ),
    new ProductClass(
        6,
        'card_10.jpg',
        'Product 6',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        32.00,
    ),
    new ProductClass(
        7,
        'card_11.jpg',
        'Product 7',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        92.00,
    ),
    new ProductClass(
        8,
        'card_12.jpg',
        'Product 8',
        'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        22.00,
    ),
]